apiVersion: v1
kind: Service
metadata:
  name: <name of a service>
  labels:
    run: <name of a run-service>
spec:
  type: NodePort 
  ports:
  - port: 8080
    nodePort: 30082
    protocol: TCP
    name: https
  selector:
    run: <name of a run-service>
---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: <name of a run-service>
spec:
  selector:
    matchLabels:
      run: <name of a run-service>
  replicas: 1
  template:
    metadata:
      labels:
        run: <name of a run-service>
    spec: 
      containers: 
        - name: <container-name>
          ports:
            - containerPort: <port of container>
          image: <image from docker hub or any private registry>
          env: 
          - name: *****
            value: *****
          - name: *****
            value: *****
        - name: <container-name>
          ports:
            - containerPort: <port of container>
          image: <image from docker hub or any private registry
          securityContext:
            privileged: true 
          env:
          - name: KEY
            value: FROMKEY
          - name: SECRET
            value: FROMSECRET
          volumeMounts:
            - name: <mount-volume-name>
              mountPath: /var/run
              subPath: var/run
      volumes:
        - name: <volume-name>
          persistentVolumeClaim:
            claimName: <claim-name>

---
