apiVersion: v1
kind: PersistentVolume
metadata:
  name: <pv-name>
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
      path: /var/run
      type: DirectoryOrCreate
  hostPath:
      path: /var/run/docker.sock
      type: DirectoryOrCreate
