apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <pv-name>
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: <pv-name>


